services:
  db:
    image: postgres:17.2-alpine
    container_name: BhayanakCastDB
    # No need to override to root—the image handles permissions as 'postgres'
    ports:
      - 3232:3232
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bhayanak
      PGPORT: "3232"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
  server:
    image: ghcr.io/thehimanshushekhar/bhayanakcast:latest
    container_name: BhayanakCastServer
    depends_on:
      - db
    ports:
      - 3434:3434
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:bhayanak@db:3232
      PORT: "3434"
    restart: unless-stopped
volumes:
  # Named volume avoids host-FS permission issues
  dbdata: null
