/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SigninImport } from './routes/signin'
import { Route as IndexImport } from './routes/index'
import { Route as RoomRoomidRoomnameImport } from './routes/room.$roomid.$roomname'

// Create/Update Routes

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RoomRoomidRoomnameRoute = RoomRoomidRoomnameImport.update({
  id: '/room/$roomid/$roomname',
  path: '/room/$roomid/$roomname',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/room/$roomid/$roomname': {
      id: '/room/$roomid/$roomname'
      path: '/room/$roomid/$roomname'
      fullPath: '/room/$roomid/$roomname'
      preLoaderRoute: typeof RoomRoomidRoomnameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/room/$roomid/$roomname': typeof RoomRoomidRoomnameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/room/$roomid/$roomname': typeof RoomRoomidRoomnameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/room/$roomid/$roomname': typeof RoomRoomidRoomnameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signin' | '/room/$roomid/$roomname'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/room/$roomid/$roomname'
  id: '__root__' | '/' | '/signin' | '/room/$roomid/$roomname'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  RoomRoomidRoomnameRoute: typeof RoomRoomidRoomnameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  RoomRoomidRoomnameRoute: RoomRoomidRoomnameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/signin",
        "/room/$roomid/$roomname"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/room/$roomid/$roomname": {
      "filePath": "room.$roomid.$roomname.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
