/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as JoinInviteTokenRouteImport } from './routes/join/$inviteToken'
import { Route as PastRoomIdRouteImport } from './routes/past/$roomId'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as RoomRoomIdRouteImport } from './routes/room/$roomId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOgRoomRoomIdRouteImport } from './routes/api/og/room/$roomId'
import { Route as ApiThumbnailsRoomIdIndexRouteImport } from './routes/api/thumbnails/$roomId/index'
import { Route as ApiThumbnailsRoomIdUserIdRouteImport } from './routes/api/thumbnails/$roomId/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinInviteTokenRoute = JoinInviteTokenRouteImport.update({
  id: '/join/$inviteToken',
  path: '/join/$inviteToken',
  getParentRoute: () => rootRouteImport,
} as any)
const PastRoomIdRoute = PastRoomIdRouteImport.update({
  id: '/past/$roomId',
  path: '/past/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoomRoomIdRoute = ApiOgRoomRoomIdRouteImport.update({
  id: '/api/og/room/$roomId',
  path: '/api/og/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThumbnailsRoomIdIndexRoute =
  ApiThumbnailsRoomIdIndexRouteImport.update({
    id: '/api/thumbnails/$roomId/',
    path: '/api/thumbnails/$roomId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiThumbnailsRoomIdUserIdRoute =
  ApiThumbnailsRoomIdUserIdRouteImport.update({
    id: '/api/thumbnails/$roomId/$userId',
    path: '/api/thumbnails/$roomId/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/health': typeof ApiHealthRoute
  '/join/$inviteToken': typeof JoinInviteTokenRoute
  '/past/$roomId': typeof PastRoomIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/room/$roomId': typeof ApiOgRoomRoomIdRoute
  '/api/thumbnails/$roomId/$userId': typeof ApiThumbnailsRoomIdUserIdRoute
  '/api/thumbnails/$roomId/': typeof ApiThumbnailsRoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/health': typeof ApiHealthRoute
  '/join/$inviteToken': typeof JoinInviteTokenRoute
  '/past/$roomId': typeof PastRoomIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/room/$roomId': typeof ApiOgRoomRoomIdRoute
  '/api/thumbnails/$roomId/$userId': typeof ApiThumbnailsRoomIdUserIdRoute
  '/api/thumbnails/$roomId': typeof ApiThumbnailsRoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/health': typeof ApiHealthRoute
  '/join/$inviteToken': typeof JoinInviteTokenRoute
  '/past/$roomId': typeof PastRoomIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/room/$roomId': typeof ApiOgRoomRoomIdRoute
  '/api/thumbnails/$roomId/$userId': typeof ApiThumbnailsRoomIdUserIdRoute
  '/api/thumbnails/$roomId/': typeof ApiThumbnailsRoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/health'
    | '/join/$inviteToken'
    | '/past/$roomId'
    | '/profile/$userId'
    | '/room/$roomId'
    | '/api/auth/$'
    | '/api/og/room/$roomId'
    | '/api/thumbnails/$roomId/$userId'
    | '/api/thumbnails/$roomId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/health'
    | '/join/$inviteToken'
    | '/past/$roomId'
    | '/profile/$userId'
    | '/room/$roomId'
    | '/api/auth/$'
    | '/api/og/room/$roomId'
    | '/api/thumbnails/$roomId/$userId'
    | '/api/thumbnails/$roomId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/health'
    | '/join/$inviteToken'
    | '/past/$roomId'
    | '/profile/$userId'
    | '/room/$roomId'
    | '/api/auth/$'
    | '/api/og/room/$roomId'
    | '/api/thumbnails/$roomId/$userId'
    | '/api/thumbnails/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiHealthRoute: typeof ApiHealthRoute
  JoinInviteTokenRoute: typeof JoinInviteTokenRoute
  PastRoomIdRoute: typeof PastRoomIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOgRoomRoomIdRoute: typeof ApiOgRoomRoomIdRoute
  ApiThumbnailsRoomIdUserIdRoute: typeof ApiThumbnailsRoomIdUserIdRoute
  ApiThumbnailsRoomIdIndexRoute: typeof ApiThumbnailsRoomIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$inviteToken': {
      id: '/join/$inviteToken'
      path: '/join/$inviteToken'
      fullPath: '/join/$inviteToken'
      preLoaderRoute: typeof JoinInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past/$roomId': {
      id: '/past/$roomId'
      path: '/past/$roomId'
      fullPath: '/past/$roomId'
      preLoaderRoute: typeof PastRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/room/$roomId': {
      id: '/api/og/room/$roomId'
      path: '/api/og/room/$roomId'
      fullPath: '/api/og/room/$roomId'
      preLoaderRoute: typeof ApiOgRoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/thumbnails/$roomId/': {
      id: '/api/thumbnails/$roomId/'
      path: '/api/thumbnails/$roomId'
      fullPath: '/api/thumbnails/$roomId/'
      preLoaderRoute: typeof ApiThumbnailsRoomIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/thumbnails/$roomId/$userId': {
      id: '/api/thumbnails/$roomId/$userId'
      path: '/api/thumbnails/$roomId/$userId'
      fullPath: '/api/thumbnails/$roomId/$userId'
      preLoaderRoute: typeof ApiThumbnailsRoomIdUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiHealthRoute: ApiHealthRoute,
  JoinInviteTokenRoute: JoinInviteTokenRoute,
  PastRoomIdRoute: PastRoomIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOgRoomRoomIdRoute: ApiOgRoomRoomIdRoute,
  ApiThumbnailsRoomIdUserIdRoute: ApiThumbnailsRoomIdUserIdRoute,
  ApiThumbnailsRoomIdIndexRoute: ApiThumbnailsRoomIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
