/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RoomRoomidImport } from './routes/room.$roomid'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RoomRoomidRoute = RoomRoomidImport.update({
  id: '/room/$roomid',
  path: '/room/$roomid',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/room/$roomid': {
      id: '/room/$roomid'
      path: '/room/$roomid'
      fullPath: '/room/$roomid'
      preLoaderRoute: typeof RoomRoomidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/room/$roomid': typeof RoomRoomidRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/room/$roomid': typeof RoomRoomidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/room/$roomid': typeof RoomRoomidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/room/$roomid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/room/$roomid'
  id: '__root__' | '/' | '/room/$roomid'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomRoomidRoute: typeof RoomRoomidRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomRoomidRoute: RoomRoomidRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/room/$roomid"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/room/$roomid": {
      "filePath": "room.$roomid.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
